### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by AugustDev** [cometchat/chat-sdk-ios#82]
It doesn't seem that Comet Chat supports SPM. Please considered implementing. Many people have moved projects away from cocopods as SPM now supports binaries. Lack of SPM support for modern project is one of the biggest reasons not to use the product right now.

**Comment by proveshapyne** [comment]
Hi @AugustDev,

We have reached out to your email for more information on this. I would appreciate it if we could continue our conversation there and therefore, I am closing out this ticket.

Thank you.

Regards,
Provesha

**Comment by pushpsenairekar2911** [comment]
Hello @acarrera94, 

We have released the SPM support for CometChat Messaging SDK v3.0.3. 
You can add a package using this link https://github.com/cometchat-pro/ios-chat-sdk.git. 

If you want to add calls as well then the calling SDK is only available via cocoa pods. 

I hope this helps. 

Regards, 
Pushpsen R. Airekar

**Comment by LaurentiuUngur** [comment]
What about `CometChatCalls` as it's separated right now ? Is there any chance to integrate it as well with SPM ? Thank you !

**Comment by pushpsenairekar2911** [comment]
Hi, 

Currently for calls SDK `CometChatCalls`  there is no support for the SPM, you can integrate it via pods. 

Regards, 
Pushpsen R. Airekar

**Comment by ketanyekale** [comment]
The SPM support has been added for  [CometChatCalls](https://github.com/cometchat-pro/ios-calls-sdk.git)
