### ISSUE TITLE
This SDK is not supported by the compiler

### ISSUE THREAD

**Issue by emmismtv** [cometchat/chat-sdk-ios#83]
Failed to build module 'CometChatPro'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.

**Comment by pushpsenairekar2911** [comment]
Hello, 

Can you please specify which Xcode version are you using, We have tried with Xcode 13 and it's working as expected. 
Also, please provide us the more details so that we can look into this. 

Regards, 
Pushpsen R. Airekar

**Comment by proveshapyne** [comment]
Hello @emmismtv,

I am closing this ticket due to inactivity. Please write to us at help@cometchat.com if you still need a hand with this.
Thank you.

Regards,
Provesha
